name: Test project
on: [push]
jobs:
  testRunnerInEditMode:
    name: Test edit mode ðŸ“
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}   
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decrypt the license file	
        run: openssl aes-256-cbc -d -in .github/Unity_v2020.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2020.x.ulf	

        # Activate unity	
      - name: Activate Unity	
        run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2020.x.ulf || exit 0

      - name: Run tests
        uses: MirrorNG/unity-runner@2.0.0
        with:
          args: -runTests -projectPath .
#tes
